// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xisylfkrswysjyvrdhen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpc3lsZmtyc3d5c2p5dnJkaGVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MzU0MzksImV4cCI6MjA2MjQxMTQzOX0._FqNybw33RDxaA_NiPvLv3sJhYhpjpcsuSJyW-Z3GNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);